cooler readme.md
Funtimes909/ServerSeekerV2-Java pull request #3
Opened 2024-11-19 11:50 UTC by Waitlists

i luv serverseekerv2

2024-11-19 12:56 UTC, EngurRuzgar requested changes

2024-11-19 12:56 UTC, EngurRuzgar commented on README.md
> +- Self-hostable (Host your own scanner and database!)
The phrase "Self Hosted" or "Self Hostable" should have their words separate.

2024-11-19 12:56 UTC, EngurRuzgar commented on README.md
> +- Ability to detect if (some) servers are running in cracked mode
Either "in offline mode" or "as a cracked server"

2024-11-20 01:19 UTC, Funtimes909 commented
Your commit names are not funny, also these seem like little nitpick changes that aren't worth a pull request

2024-11-20 01:19 UTC, closed without merging